str = "Sheikh Irtiza"
print(str)
print(str[0])
print(str[1])
print(str[2])
print(str[3])
print(str[4])
print(str[5])
print(str[6])
print(str[7])
print(str[8])
print(str[9])
print(str[10])
print(str[11])
print(str[12])
print(str[0:2])
print(str[2:])
print(str * 3)
print(str[7:])
print(str + "Shafi")
